import type { DenizenData } from "../components/entityComponents/entityData";
import {
    DenizenRole,
    DenizenStatus,
    DenizenType,
} from "../components/entityComponents/entityData";

export interface DenizenOffer {
    type: DenizenType;
    role: DenizenRole;
    name: string;
    mark: string;
    description: string;
    cost: number;
    health: number;
    attack: number;
    defense: number;
    gatheringPower: number;
}

export type DefenderOffer = DenizenOffer;

export const DENIZEN_OFFERS: readonly DenizenOffer[] = [
    {
        type: DenizenType.GOBLIN,
        role: DenizenRole.DEFENDER,
        name: "Goblin Skirmisher",
        mark: "G",
        description: "Cheap, quick muscle for filling an exposed guard room.",
        cost: 15,
        health: 55,
        attack: 12,
        defense: 4,
        gatheringPower: 0,
    },
    {
        type: DenizenType.SKELETON,
        role: DenizenRole.DEFENDER,
        name: "Skeleton Guard",
        mark: "S",
        description: "A dependable defender with balanced staying power.",
        cost: 25,
        health: 80,
        attack: 16,
        defense: 8,
        gatheringPower: 0,
    },
    {
        type: DenizenType.ORC,
        role: DenizenRole.DEFENDER,
        name: "Orc Brute",
        mark: "O",
        description: "Expensive frontline strength built to hold a chamber.",
        cost: 40,
        health: 125,
        attack: 24,
        defense: 12,
        gatheringPower: 0,
    },
    {
        type: DenizenType.SLIME,
        role: DenizenRole.GATHERER,
        name: "Slime Extractor",
        mark: "P",
        description:
            "A steady producer that improves every resource generated by its room.",
        cost: 18,
        health: 45,
        attack: 4,
        defense: 3,
        gatheringPower: 1.5,
    },
] as const;

export const DEFENDER_OFFERS = DENIZEN_OFFERS.filter(
    (offer) => offer.role === DenizenRole.DEFENDER,
);

export const PRODUCER_OFFERS = DENIZEN_OFFERS.filter(
    (offer) => offer.role === DenizenRole.GATHERER,
);

export function createDenizen(offer: DenizenOffer, id: string): DenizenData {
    return {
        id,
        type: offer.type,
        role: offer.role,
        status: DenizenStatus.ACTIVE,
        assignedRoomId: null,
        level: 1,
        health: offer.health,
        maxHealth: offer.health,
        attack: offer.attack,
        defense: offer.defense,
        experience: 0,
        gatheringPower: offer.gatheringPower,
        recoveryRemainingMs: 0,
        position: { x: 0, y: 0 },
        size: { width: 24, height: 24 },
    };
}

export function createDefender(offer: DenizenOffer, id: string): DenizenData {
    return createDenizen(offer, id);
}
